database_task:
  description: >
    Connect to the space resource database, fetch all relevant data from the 'resources' table—including current resource utilisation and historical mission consumption metrics.
    Pre-process and structure the data for analysis and downstream tasks.
    Additionally, perform an anomaly check by comparing real‑time data with historical trends to flag any insufficiencies in resource allocation.
  expected_output: >
    A structured dataset (formatted as a list or table) that includes:
      - Current resource levels and consumption rates,
      - Historical consumption metrics from previous missions,
      - Flags or alerts indicating any detected anomalies or resource insufficiencies.
    This dataset should be ready for use by other agents for research and resource management.
  agent: database_agent

research_task:
  description: >
    Conduct comprehensive online research to identify possible reasons behind observed resource anomalies and insufficiencies.
    Analyze both current resource data and historical consumption trends to understand factors contributing to these issues.
    Gather actionable suggestions and recommendations from reputable sources to support resource management decisions.
  expected_output: >
    A list of 3 bullet points summarising the key research findings, where each bullet includes:
      - A concise explanation of potential causes behind the resource anomalies.
      - Practical suggestions or remedial actions recommended by experts or relevant sources.
      - Additional insights to support informed decision-making in space resource management.
  agent: researcher

mission_integration_task:
  description: >
    Analyze current mission objectives, operational timelines, and available resource data—including both current 
    resource levels and historical consumption metrics—to generate a highly accurate prediction of resource consumption for the upcoming mission.
  expected_output: >
    A concise prediction report summarising the expected consumption of key resources (e.g., fuel, power, oxygen) for the upcoming mission.
  agent: mission_integration_strategist

resource_management_task:
  description: >
    Based on the anomaly reports and resource consumption predictions provided by other agents,
    develop a high-level resource allocation strategy for upcoming missions.
    Your task is to integrate these insights to decide on optimal adjustments for distributing critical assets (e.g., fuel, power, oxygen)
    without re-analyzing the raw data.
  expected_output: >
    A concise set of bullet points outlining:
      - Recommended adjustments for resource allocation,
      - Identification of any insufficiencies and suggested remedial actions,
      - A high-level strategy ensuring that resource distribution aligns with mission-critical objectives.
  agent: resource_management_specialist

reporting_task:
  description: >
    Collate and analyse data from previous tasks—including research findings, real-time resource management outcomes, and detected anomalies—to generate a comprehensive report on space resource management.
    The report should include detailed sections on:
      - Current resource status and consumption,
      - Anomalies detected in resource usage,
      - Predictive analytics outcomes from mission_integration_strategist,
      - Resource management outcomes from resource_management_specialist.
    Focus on presenting an accurate snapshot of the current operational state without prescribing future actions.
  expected_output: >
    A fully detailed report formatted in markdown (without using '```') that includes distinct sections covering:
      - Real-time analysis of current resource data and consumption,
      - Analysis and explanation of any detected anomalies,
      - Results and insights from predictive analytics and resource management actions.
      - Key research findings on space resource management,
  agent: reporting_analyst




# anomaly_contingency_task:
#   description: >
#     Monitor simulated or historical resource usage data to detect anomalies or unexpected resource drains.
#     Develop a set of contingency plans that can be triggered automatically when such anomalies are detected.
#   expected_output: >
#     A list of contingency recommendations and decision rules formatted as bullet points, detailing corrective actions and fallback strategies for resource management.
#   agent: anomaly_contingency_manager
